dist: trusty
sudo: false
language: java

jdk:
  - oraclejdk8
  - openjdk8
  #- oraclejdk9

os:
  - linux

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      env: DOCKERIZED_JAVA=TRUE
      services: 
        - docker
        - haveged
      

services:
  - haveged

install: true

script:
  - ls -la /usr/lib/jvm
  - echo $JAVA_HOME
  - ls -l $JAVA_HOME
  - which java
  - which javac
  - java -version
  - if [ "$DOCKERIZED_JAVA" == "TRUE" ] ; then
          echo "using dockerized maven";
          docker pull maven:3.5.2-ibmjava-8;
          docker run -it --rm --volume "$PWD"/pom.xml://usr/src/app/pom.xml --volume "$HOME"/.m2:/root/.m2 maven:3.5.2-ibmjava-8 mvn -v clean;
    else
          echo "using default maven";
          mvn -v clean;
    fi
