dist: trusty
sudo: false
language: java


jdk:
  - oraclejdk8
  - openjdk8
  
os:
  - linux

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      group: edge
      jdk: ibmjava8

addons:
  postgresql: "9.6"
  hostname: flamingo
  hosts:
    - flamingo
  apt:
    packages:
      - haveged
      - git-lfs

services:
  - haveged

before_install:
  - export PAGER=cat
  - echo $JAVA_HOME
  - java -v  

install: true

script:
  - mvn -v
