dist: trusty
sudo: required
language: java

jdk:
  - openjdk8

os:
  - linux

matrix:
  fast_finish: true

      
install: true

script:
# load pki o G2/G3 certs
  - wget http://cert.pkioverheid.nl/RootCA-G3.cer
  - sudo keytool -importcert -file ./RootCA-G3.cer -alias G3 -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass 'changeit' -v -noprompt -trustcacerts
  - wget http://cert.pkioverheid.nl/RootCA-G2.cer
  - sudo keytool -importcert -file ./RootCA-G2.cer -alias G2 -keystore $JAVA_HOME/jre/lib/security/cacerts -storepass 'changeit' -v -noprompt -trustcacerts

