dist: trusty
sudo: false
language: java

jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9

os:
  - linux

matrix:
  fast_finish: true
  include:
    - os: linux
      sudo: required
      group: edge
      jdk: ibmjava8

services:
  - haveged

install: true

script:
  - echo $JAVA_HOME
  - ls -l $JAVA_HOME
  - which java
  - which javac
  - mvn -v
