version: 1.0.{build}
skip_tags: true
image: Visual Studio 2017
clone_depth: 5

environment:
  fast_finish: true

  matrix:
    - JDK: JDK8
      JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - cmd: echo %PATH%
# load pki o G2/G3 certs
  - ps: Invoke-WebRequest http://cert.pkioverheid.nl/RootCA-G2.cer -OutFile .\RootCA-G2.cer
  - cmd: keytool -importcert -file .\RootCA-G2.cer -alias G2 -keystore "%JAVA_HOME%\jre\lib\security\cacerts" -storepass changeit -v -noprompt -trustcacerts
  - ps: Invoke-WebRequest http://cert.pkioverheid.nl/RootCA-G3.cer -OutFile .\RootCA-G3.cer
  - cmd: keytool -importcert -file .\RootCA-G3.cer -alias G3 -keystore "%JAVA_HOME%\jre\lib\security\cacerts" -storepass changeit -v -noprompt -trustcacerts

build: off

test: off
